### PR TITLE
Log and print important debugging information in BE

### PR DESCRIPTION
**Pull request by schivmeister**
We need visibility into the important steps and processes of the API, long-running or not.

For code where `print()` is already in use, continue printing out. Elsewhere, log out reusing the server's (`uvicorn`) default logger.

### CODE REVIEW

**Review by kaleanych — APPROVED** [review]

**Comment by schivmeister** [comment]
This does not appear to work _completely_ against the latest changes adding the task runner (I tested against an older revision before that). None of the logger statements are coming out, and only _some_ of the print statements are there.

@kaleanych any ideas?

**Comment by kaleanych** [comment]
Where do you want to display the logs?

**Comment by schivmeister** [comment]
> Where do you want to display the logs?

Simply along with all the log information coming out of the BE/API right now. At commit 88e70ca we are able to see all the log statements produced using the `uvicorn` logger. However, this doesn't work in main now. I don't know which logger will work.

I have rebased this work against that known working commit for now. It is however safe to merge against main, as only the debug statements won't come out. I still recommend fixing that before merging this.

**Comment by schivmeister** [comment]
Note that using `logger = logging.getLogger("asyncio")` does _not_ work either. If we cannot find a solution, I can revert all logging statements to print().

**Comment by schivmeister** [comment]
This appears to work but obviously it's skipping the format of the server (uvicorn) log:

```
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger()
```

Perhaps then the logging configuration is the issue. We want to be able to log both outside and inside async/await processes.

References:
- https://superfastpython.com/asyncio-log-blocking/
- https://www.zopatista.com/python/2019/05/11/asyncio-logging/
- https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes

File writing is not important, only stdout/stderr. From the last reference:

> When deploying Web applications using [Gunicorn](https://gunicorn.org/) or [uWSGI](https://uwsgi-docs.readthedocs.io/en/latest/) (or similar), multiple worker processes are created to handle client requests. In such environments, avoid creating file-based handlers directly in your web application. Instead, use a [SocketHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.SocketHandler) to log from the web application to a listener in a separate process. This can be set up using a process management tool such as Supervisor - see [Running a logging socket listener in production](https://docs.python.org/3/howto/logging-cookbook.html#running-a-logging-socket-listener-in-production) for more details.

**Review by kaleanych — APPROVED** [review]

**Pull request merged**
