### PR TITLE
feature/MWB-470

### PR DESCRIPTION
**Pull request by SilverBerserk**

### CODE REVIEW

**Review by duprijil — APPROVED** [review]

**Review by kaleanych — APPROVED** [review]

**Review by schivmeister — CHANGES_REQUESTED** [review]
- It appears **Source Schema** and **Target Ontology** have switched sides
- I think it would be helpful to append `(eForms)` to the JSON **Type** value
- Spelling for `Triger` should be "Trig**g**er"; instead of "Trigger" use `Run`, but I think we should rewrite the labels altogether.
    - Reword the `Namespace Discovery` option label to **Automatically discover namespaces**
    - Reword the `Specific Namespaces` option label to **Add custom namespaces**
        - It does not make sense to show `Specific Namespaces` option without allowing to specify the namespaces, so it should be some kind of input field if checked (and added to the custom list @kaleanych planned to implement)
            - Whether or not this is a plain text field or some other structure needs to be discussed w/ @kaleanych 
        - Depending on @kaleanych's implementation of namespace and prefix management, this may not be required (so we need to know where is on that)

image

**Review by schivmeister — CHANGES_REQUESTED** [review]
The namespace discovery fails, although custom namespaces are added, which themselves are wrong.

@csnyulas has suggested to use the `prefix_definitions` from [this list](https://github.com/OP-TED/ted-rdf-conversion-pipeline/blob/main/ted_sws/resources/prefixes/prefixes.json) (except the ones in `currently_unused`).

The namespace discovery task fails with the following message:

```
2 validation errors for Namespace uri Field required [type=missing, input_value={'prefix': 'brick'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.7/v/missing is_syncable Field required [type=missing, input_value={'prefix': 'brick'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.7/v/missing
```

**Comment by SilverBerserk** [comment]
> * It appears **Source Schema** and **Target Ontology** have switched sides
> * I think it would be helpful to append `(eForms)` to the JSON **Type** value
> * Spelling for `Triger` should be "Trig**g**er"; instead of "Trigger" use `Run`, but I think we should rewrite the labels altogether.
>   
>   * Reword the `Namespace Discovery` option label to **Automatically discover namespaces**
>   * Reword the `Specific Namespaces` option label to **Add [eForms](https://github.com/OP-TED/eforms-sdk)-specific ([ePO](https://github.com/OP-TED/ePO)) namespaces**
>     
>     * Depending on @kaleanych's implementation of namespace and prefix management, this may not be required (so we need to know where is on that). For e.g., if he already adds the ePO-specific namespaces to the auto-discovery process.
> 
> image

**Comment by duprijil** [comment]
I have this error when trying to create a project.
image

**Comment by schivmeister** [comment]
> I have this error when trying to create a project.

Yes, same error:

```
Request failed with status code 422
Extra inputs are not permitted
```

**Comment by schivmeister** [comment]
@SilverBerserk @duprijil discover terms task still fails

```
2 validation errors for Namespace uri Field required [type=missing, input_value={'prefix': 'brick'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.7/v/missing is_syncable Field required [type=missing, input_value={'prefix': 'brick'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.7/v/missing
```

**Comment by duprijil** [comment]
@schivmeister I manage to solve the problems. This PR can be merged

**Pull request merged**
